POST http://localhost:8000/auth/sign-in
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###
POST http://localhost:8000/auth/sign-up
Content-Type: application/json

{
  "firstName": "artem",
  "lastName": "golovanov",
  "username": "test",
  "password": "test",
  "email": "test@test.ru"
}

###
GET http://localhost:8000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0QHRlc3QucnUiLCJyb2xlcyI6IlJPTEVfVVNFUiIsInN1YiI6InRlc3QiLCJpYXQiOjE3NDY4NzU5MzIsImV4cCI6MTc0NzAxOTkzMn0.8O8q4nTfBujZasrr3j3CtTni6kyrJRKizPOFcsIAXMc

###
GET http://localhost:8000/api/course
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0QHRlc3QucnUiLCJyb2xlcyI6IlJPTEVfVVNFUiIsInN1YiI6InRlc3QiLCJpYXQiOjE3NDY4NzU5MzIsImV4cCI6MTc0NzAxOTkzMn0.8O8q4nTfBujZasrr3j3CtTni6kyrJRKizPOFcsIAXMc